### ISSUE TITLE
`mbti.poolc.kr:3001` is running dev server, but should be production

### ISSUE THREAD

**Issue by maxswjeon** [mumwa/poolc-frontend-mbti#1]
mbti.poolc.kr:3001 is running as a dev server (probably running `npm run dev` on a EC2 since 13.125.106.9 is a EC2 IP)

This exposes vulnerable paths, such as,
- http://watch.jimmy0006.site:3002/
- /home/vsfe/poolc-frontend-mbti (The root folder of the project in the server)

**Comment by QuqqU** [comment]
- 13.125.106.9 서버는 EC2가 아닙니다. 
- 해당 서버는 실물 서버로, 개인정보를 포함해 어떠한 의미있는 정보가 저장되지 않습니다. 연습용 개발 서버입니다.
- 해당 레포지토리는 동아리 박람회용 간이 프로그램을 담고 있습니다. 배포용이 아니기 때문에 굳이 prod일 필요 없습니다.
- 설령 보안문제가 있더라도, private하게 알리는 것이 일반적입니다.

더불어 우리 동아리에 관심이 많은 것은 환영하지만, 이런 식의 관심은 사양합니다.

**Comment by VSFe** [comment]
안녕하세요.

이번 동아리 박람회의 프로젝트에는 어떠한 기여도 하지 않았고 어떤 일이 있었는지도 잘 모르지만, 카톡 메시지를 저에게 보냈었던지라 저도 짧게 메시지 남기고 갑니다.

위에서 @QuqqU 님이 말씀해주신 것 처럼, 동아리 보유 실물 서버에 로컬처럼 작업한 프로젝트로, 어떠한 개인정보도 포함되어 있지도 않으며 주로 교육용으로 사용됩니다.
 
해당 프로젝트를 수행한 Contributor는 FE 개발에 많은 관심을 갖고 있고, 이미 이전에도 많은 프로젝트를 경험하면서 당연히 수많은 배포 프로세스도 경험했을 것 입니다. 몰라서 dev로 배포한 것이 아닌, production 으로 할 이유가 없으니 안 한 것이겠죠.

정말로 보안이 걱정되어서 이슈를 올린건지, 아니면 모르는 것 같으니 가르쳐주려는 교화 목적으로 이런 이슈를 올리신건지는 모르겠지만, 이슈를 통한 지적은 다소 좋은 방법이 아닌 것 같습니다.

순수하게 걱정되는 목적이라도, 현재 상완님이 YCC 임원으로 소속되어 있기 때문에 이런 이슈는 다른 동아리에 대한 예의가 아닌 것 같아 다소 조심스럽습니다.

**Comment by maxswjeon** [comment]
안녕하세요.

먼저 죄송하다는 말씀 드리고 싶습니다.
당시에 동아리 박람회라는 행사가 진행되고 있었던 점, 그리고 우연히 YCC에서 준비한 컨텐츠와 PoolC측에서 준비해주신 컨텐츠가 겹쳤던 점 등으로 인해 개인적으로 흥미를 가졌고, 이로 인해 선을 넘은 것에 대해 죄송합니다.

이 행동은 개인적인 행동이며, YCC에서 공식적으로나 다수의 의견에 의한 것이 전혀 아니며 저 개인적으로 진행하였습니다.

제 행동을 다시 돌아보니 충분히 불쾌하실 수 있을 것 같습니다. 정말 죄송합니다.

저때문에 YCC와 PoolC간 불편한 일이 없었으면 좋겠습니다. 죄송합니다.

지적해주신 점 감사합니다.
